#ifndef __SGDL_ERROR_CODES_H
#define __SGDL_ERROR_CODES_H

enum SGDL_CODE {
	SGDL_E_OK,
	SGDL_E_BAD_ID,
	SGDL_E_FETCH_URL_ERR,
	SGDL_E_NO_MATCH,
	SGDL_E_REGCOMP,
	SGDL_E_OPTION_ERR,
	SGDL_E_MALLOC_ERR,
	SGDL_E_CURL_ERR,
	SGDL_E_ERR
};

#endif
